services:
  test_db:
    image: postgres:16
    restart: always
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend_test_net

  test_backend:
    build:
      context: .
      dockerfile: test.Containerfile
    depends_on:
      - test_db
    networks:
      - backend_test_net

networks:
  backend_test_net:
    driver: bridge
