// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbc

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID    uuid.UUID
	Email string
}

type Config struct {
	ID            uuid.UUID
	Slug          string
	ConfigSection []byte
	UpdatedAt     time.Time
}

type Person struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	FirstName string
	LastName  string
}
