// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConfigsGet(ctx context.Context, slugs string) ([][]byte, error)
	CreateAccount(ctx context.Context, email string) (uuid.UUID, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (uuid.UUID, error)
	GetAccountsByEmail(ctx context.Context, emails []string) ([]*GetAccountsByEmailRow, error)
	SaveConfig(ctx context.Context, arg SaveConfigParams) error
}

var _ Querier = (*Queries)(nil)
